import { NoctEvent } from "./types";

export const SAMPLE_EVENTS: NoctEvent[] = [
  {
    source: "zilesinopti",
    title: "corp.: Admina, Chlorys & von Bulove @ Control Club",
    venue: "Control Club",
    date: "2026-03-08",
    time: "19:00",
    description: "Front Room session. Admina channels queer feminist energy into loud, playful and unapologetic club pressure, weaving experimental textures through a...",
    image_url: "https://zilesinopti.ro/wp-content/uploads/2026/03/corp.-Admina-Chlorys-von-Bulove-@-Control-Club-1024x536.jpg",
    event_url: "https://zilesinopti.ro/evenimente/admina-chlorys-von-bulove/",
    genres: ["Electronic", "Techno", "House", "Experimental", "Minimal"],
    price: "Free",
  },
  {
    source: "iabilet",
    title: "Ladies Night x BDLP",
    venue: "OXYA Club",
    date: "2026-03-08",
    time: null,
    description: "Ladies Night reprezinta unul dintre cele mai asteptate evenimente din club OXYA Bucuresti! Featuring BDLP.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/dc/1b/00000383065-d9a9.jpg",
    event_url: "https://www.iabilet.ro/bilete-ladies-night-x-bdlp-121883/",
    genres: ["Club", "Party"],
    price: null,
  },
  {
    source: "livetickets",
    title: "Vlad Flueraru - Lansare Album 'Pedralba' - 12.03",
    venue: "Control Club",
    date: "2026-03-12",
    time: "19:00",
    description: "Vlad Flueraru album launch at Control Club Bucharest - one of Bucharest's cult underground venues.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/vlad-flueraru-lansare-album-pedralba-1203/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/vlad-flueraru-lansare-album-pedralba-1203",
    genres: ["Live Music", "Alternative"],
    price: "50 - 100 RON",
  },
  {
    source: "livetickets",
    title: "CARAMELO | baila reggaeton",
    venue: "Interbelic",
    date: "2026-03-12",
    time: "20:00",
    description: "Reggaeton and Latin dance night at Interbelic Bucharest. Free entry.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/caramelo-baila-reggaeton-39/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/caramelo-baila-reggaeton-39",
    genres: ["Reggaeton", "Latin", "Hip-Hop"],
    price: "de la 0 RON",
  },
  {
    source: "zilesinopti",
    title: "PW - Misbits 13 Years Anniversary - Raresh, Miss I, oddist @ Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-13",
    time: "22:00",
    description: "The biggest anniversary party for Misbits record shop's 13th anniversary. Featuring Raresh, one of Romania's most renowned minimal/techno DJs...",
    image_url: "https://zilesinopti.ro/wp-content/uploads/2026/02/PW-%E2%80%A2-Misbits-13-Years-Anniversary-%E2%80%A2-Raresh-Miss-I-oddist-@-Platforma-Wolff-1024x536.jpg",
    event_url: "https://zilesinopti.ro/evenimente/raresh-miss-i-oddist-platforma-wolff/",
    genres: ["Minimal", "Techno", "House", "Underground Electronic"],
    price: "70 - 90 RON",
  },
  {
    source: "livetickets",
    title: "BLOOM - Maison64 Only300",
    venue: "Maison 64",
    date: "2026-03-13",
    time: "22:00",
    description: "Exclusive limited-capacity (300 people) club night at Maison 64 Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/bloom-maison64-only300/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/bloom-maison64-only300",
    genres: ["Club", "Nightlife"],
    price: "de la 80 RON",
  },
  {
    source: "livetickets",
    title: "CAROUSEL PARTY / 13 Martie @ NOAR HALL, Bucuresti",
    venue: "Noar Hall",
    date: "2026-03-13",
    time: "22:00",
    description: "Carousel Party at Noar Hall Bucharest - a recurring club party series.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/carousel-party-noar-hall-bucuresti/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/carousel-party-noar-hall-bucuresti",
    genres: ["Club", "Party"],
    price: "30 - 100 RON",
  },
  {
    source: "zilesinopti",
    title: "Hector Oaks [ES] @ Control Club",
    venue: "Control Club",
    date: "2026-03-13",
    time: "23:00",
    description: "Hector Oaks brings heat the old school way. Vinyl only, for a maximum of impact. Raised in Spain's 90s rave culture and sharpened by years digging...",
    image_url: "https://zilesinopti.ro/wp-content/uploads/2026/02/Hector-Oaks-ES-@-Control-Club-1024x536.jpg",
    event_url: "https://zilesinopti.ro/evenimente/hector-oaks-es-control-club/",
    genres: ["Techno", "Ghetto Tech", "Acid", "EBM", "Raw Techno"],
    price: "40 - 50 RON",
  },
  {
    source: "livetickets",
    title: "NOOKin w/ Traumer, Maher Daniel, Sepp & Nu Zau, ASHPOT",
    venue: "Nook Club",
    date: "2026-03-13",
    time: "23:00",
    description: "Underground techno night featuring Traumer, Maher Daniel (Romanian minimal legend), Sepp & Nu Zau, and ASHPOT. All-night event at Bucharest's Nook...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/nookin-w-traumer-maher-daniel-sepp-nu-zau-ashpot/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/nookin-w-traumer-maher-daniel-sepp-nu-zau-ashpot",
    genres: ["Techno", "Minimal", "Underground"],
    price: "de la 50 RON",
  },
  {
    source: "livetickets",
    title: "GRAYZONE x VIPER",
    venue: "Club Guesthouse",
    date: "2026-03-13",
    time: "23:00",
    description: "Underground club night at Club Guesthouse, one of Bucharest's premier underground venues.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/grayzone-x-viper/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/grayzone-x-viper",
    genres: ["Underground", "Club"],
    price: "35 - 45 RON",
  },
  {
    source: "iabilet",
    title: "Musiclover Party #1 @ Concert Gheboasa",
    venue: "KAYO Club",
    date: "2026-03-13",
    time: null,
    description: "Prima editie MUSICLOVER PARTY vine cu vibe-ul pe care nu vrei sa-l ratezi! Invitatul special Gheboasa aduce energia care te prinde instant.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e2/27/00000385130-9c2c.jpg",
    event_url: "https://www.iabilet.ro/bilete-musiclover-party-1-concert-gheboasa-123431/",
    genres: ["Hip-Hop", "Party"],
    price: "de la 71 RON",
  },
  {
    source: "zilesinopti",
    title: "Black Rhino Residency #25: Iration Steppas @ Control Club",
    venue: "Control Club",
    date: "2026-03-14",
    time: "22:00",
    description: "Black Rhino residency #25 featuring Iration Steppas, the Vanguard of Dub. Session amplified by Riddim Bandits Sound System. Iration Steppas Sound...",
    image_url: "https://zilesinopti.ro/wp-content/uploads/2026/02/Black-Rhino-Residency-25-Iration-Steppas-@-Control-Club-1024x536.jpg",
    event_url: "https://zilesinopti.ro/evenimente/black-rhino-residency-25-iration-steppas-control-club/",
    genres: ["Dub", "Reggae", "Sound System", "Bass Music", "Underground Bass"],
    price: null,
  },
  {
    source: "livetickets",
    title: "PW x Refuge Worldwide 5 Years - bblove, Chlorys, No Plastic, Obelix at Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-14",
    time: "22:00",
    description: "Platforma Wolff x Refuge Worldwide (Berlin community radio) 5th anniversary with bblove, Chlorys, No Plastic and Obelix.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/pw-x-refuge-worldwide-5-years-bblove-chlorys-no-plastic-obelix-at-platforma-wolff/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/pw-x-refuge-worldwide-5-years-bblove-chlorys-no-plastic-obelix-at-platforma-wolff",
    genres: ["Underground", "Electronic"],
    price: "de la 30 RON",
  },
  {
    source: "livetickets",
    title: "Amani: TULUM x Housetopia",
    venue: "Club Mono",
    date: "2026-03-14",
    time: "22:00",
    description: "Tulum-inspired house music night at Club Mono Bucharest. Housetopia vibes.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/tulum-tibute-to-keinemusik/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/tulum-tibute-to-keinemusik",
    genres: ["House", "Deep House"],
    price: "35 - 40 RON",
  },
  {
    source: "livetickets",
    title: "BUCHAREST V.I.P | GRAND OPENING",
    venue: "Princess Club",
    date: "2026-03-14",
    time: "22:00",
    description: "Grand opening event at Princess Club Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/bucharest-vip-grand-opening/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/bucharest-vip-grand-opening",
    genres: ["Club", "Nightlife"],
    price: "60 - 80 RON",
  },
  {
    source: "zilesinopti",
    title: "Cap, Christian AB & Francesco del Garda @ Club Guesthouse",
    venue: "Club Guesthouse",
    date: "2026-03-14",
    time: "23:00",
    description: "It took the right room, the right moment, and a rare alignment. March 14 at Guesthouse. No-photo clubbing policy. The club reserves the right to...",
    image_url: "https://zilesinopti.ro/wp-content/uploads/2026/02/Cap-Christian-AB-Francesco-del-Garda-@-Club-Guesthouse.jpg",
    event_url: "https://zilesinopti.ro/evenimente/cap-christian-ab-francesco-del-garda/",
    genres: ["Minimal", "Techno", "House", "Deep House"],
    price: "55 - 70 RON",
  },
  {
    source: "livetickets",
    title: "Girls Wanna Have Fun - Story The Club",
    venue: "FOMO Club",
    date: "2026-03-14",
    time: "23:00",
    description: "Club party night at FOMO Club Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/girls-wanna-have-fun-story-the-club/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/girls-wanna-have-fun-story-the-club",
    genres: ["Club", "Party"],
    price: "20 - 50 RON",
  },
  {
    source: "livetickets",
    title: "EMPYREAN EP 3",
    venue: "Oclu Pub",
    date: "2026-03-20",
    time: "19:00",
    description: "EMPYREAN Episode 3 at Oclu Pub Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/empyrean-ep-3/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/empyrean-ep-3",
    genres: ["Live Music", "Underground"],
    price: "70 - 110 RON",
  },
  {
    source: "livetickets",
    title: "Amnesia pres. Pyramid Ibiza World Tour: BUCHAREST 20.03.2026",
    venue: "Museum of Immersive New Art (MINA)",
    date: "2026-03-20",
    time: "22:00",
    description: "The iconic Amnesia Ibiza lands in Bucharest for its Pyramid World Tour. Lineup: Mason Collective, Mar-T b2b Luca Donzelli, Olive F, plus local...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/amnesia-pres-pyramid-world-tour-bucharest/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/amnesia-pres-pyramid-world-tour-bucharest",
    genres: ["Techno", "House", "Ibiza"],
    price: "90 - 300 RON",
  },
  {
    source: "livetickets",
    title: "Wolf City Bucharest",
    venue: "Forge Bucharest",
    date: "2026-03-20",
    time: "22:00",
    description: "The biggest hard dance event ever in Bucharest! Headlined by Hysta (FR) - hardcore DJ who played Thunderdome, Dominator, Defqon.1, Tomorrowland and...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/wolf-city-bucharest/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/wolf-city-bucharest",
    genres: ["Hard Dance", "Hardcore", "Hardstyle"],
    price: "50 - 195 RON",
  },
  {
    source: "livetickets",
    title: "PW x Flipside - Vass, Lowkodi, Twodoor at Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-20",
    time: "22:00",
    description: "Platforma Wolff x Flipside presents Vass, Lowkodi and Twodoor. Underground electronic night.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/pw-x-flipside-vass-lowkodi-twodoor/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/pw-x-flipside-vass-lowkodi-twodoor",
    genres: ["Underground", "Electronic"],
    price: "de la 40 RON",
  },
  {
    source: "livetickets",
    title: "Adrian Norocel - Bucuresti Centrul Vechi - Story The Club",
    venue: "FOMO Club",
    date: "2026-03-20",
    time: "22:00",
    description: "Adrian Norocel DJ set at FOMO Club in Bucharest Old Town.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/adrian-norocel-bucuresti-centrul-vechi-story-the-club/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/adrian-norocel-bucuresti-centrul-vechi-story-the-club",
    genres: ["Club", "Party"],
    price: "de la 50 RON",
  },
  {
    source: "livetickets",
    title: "Bailando - SIN PIJAMA",
    venue: "Princess Club",
    date: "2026-03-20",
    time: "22:00",
    description: "Latin and reggaeton club night at Princess Club Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/bailando-sin-pijama/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/bailando-sin-pijama",
    genres: ["Latin", "Reggaeton", "Club"],
    price: "40 - 70 RON",
  },
  {
    source: "iabilet",
    title: "Musiclover Party #2 @ Concert SHIFT",
    venue: "KAYO Club",
    date: "2026-03-20",
    time: null,
    description: "MUSICLOVER PARTY continua cu editia #2 - o noapte pentru cei care simt muzica la maxim. De data asta, vibe-ul e dus la next level de invitatul...",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e2/b4/00000385763-7989.jpg",
    event_url: "https://www.iabilet.ro/bilete-musiclover-party-2-concert-shift-123572/",
    genres: ["Hip-Hop", "Party"],
    price: "de la 71 RON",
  },
  {
    source: "livetickets",
    title: "PW - Dragos Ilici (all night long) at Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-21",
    time: "22:00",
    description: "Dragos Ilici all-night-long DJ set at Platforma Wolff. Deep underground session.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/pw-dragos-ilici-all-night-long-at-platforma-wolff/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/pw-dragos-ilici-all-night-long-at-platforma-wolff",
    genres: ["Minimal", "Techno", "Underground"],
    price: "de la 40 RON",
  },
  {
    source: "livetickets",
    title: "Alex Botea x 21 Martie x Princess Club Bucuresti",
    venue: "Princess Club",
    date: "2026-03-21",
    time: "22:00",
    description: "Alex Botea DJ night at Princess Club Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/alex-botea-x-21-martie-x-princess-club-bucuresti/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/alex-botea-x-21-martie-x-princess-club-bucuresti",
    genres: ["Club", "Party"],
    price: "60 - 70 RON",
  },
  {
    source: "iabilet",
    title: "ARCANDO @ Noisebreak 360",
    venue: "Noar Hall - Sala Palatului",
    date: "2026-03-21",
    time: "22:00",
    description: "This is 360 Drum & Bass. ARCANDO takes over the circle - a new way to feel the sound. Noisebreak's immersive 360-degree DnB experience.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/db/0b/00000377184-b14a.jpg",
    event_url: "https://www.iabilet.ro/bilete-arcando-noisebreak-360-121611/",
    genres: ["Drum & Bass"],
    price: "de la 95 RON",
  },
  {
    source: "livetickets",
    title: "Sqweez! invites Gegen",
    venue: "Forge Bucharest",
    date: "2026-03-21",
    time: "23:00",
    description: "Sqweez! joins forces with Berlin's Gegen collective. Raw techno with queer narratives. Lineup: Metaraph, Mar/us, FAUST, Radox. Performers: Ahrain...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/sqweez-invites-gegen/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/sqweez-invites-gegen",
    genres: ["Techno", "Underground", "Queer"],
    price: "50 - 210 RON",
  },
  {
    source: "livetickets",
    title: "GH 21.03 | LIMOUSINE DREAM w. Gene on Earth, Gojnea76, Jorg Kunning live, Shanti Celeste",
    venue: "Club Guesthouse",
    date: "2026-03-21",
    time: "23:00",
    description: "LIMOUSINE DREAM at Club Guesthouse with Gene on Earth, Gojnea76, Jorg Kunning (live) and Shanti Celeste. Presale 60 lei, door 80 lei. No-photo...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/gh-2103-limousine-dream-w-gene-on-earth-gojnea76-jorg-kunning-live-shanti-celeste/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/gh-2103-limousine-dream-w-gene-on-earth-gojnea76-jorg-kunning-live-shanti-celeste",
    genres: ["Minimal", "House", "Underground"],
    price: "de la 60 RON",
  },
  {
    source: "iabilet",
    title: "Athletes vs Cheerleaders x Rava & Petre Stefan",
    venue: "OXYA Club",
    date: "2026-03-21",
    time: null,
    description: "Athletes vs Cheerleaders reprezinta unul dintre cele mai asteptate evenimente din club OXYA Bucuresti! Featuring Rava & Petre Stefan.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/df/51/00000381903-0715.jpg",
    event_url: "https://www.iabilet.ro/bilete-athletes-vs-cheerleaders-x-rava-petre-stefan-122705/",
    genres: ["Club", "Party"],
    price: "de la 138 RON",
  },
  {
    source: "iabilet",
    title: "Concert PARAZITII la Quantic",
    venue: "Quantic",
    date: "2026-03-24",
    time: "21:00",
    description: "PARAZITII canta pe 24 martie la Quantic Club din Bucuresti de la ora 21:00. Primele 100 de bilete au pret earlybird. One of Romania's most iconic...",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e1/a0/00000384665-f53c.jpg",
    event_url: "https://www.iabilet.ro/bilete-concert-parazitii-la-quantic-123296/",
    genres: ["Hip-Hop", "Rap"],
    price: "de la 162 RON",
  },
  {
    source: "iabilet",
    title: "Bitza - PERSONALE - Avanpremiera Album",
    venue: "Expirat Halele Carol",
    date: "2026-03-25",
    time: null,
    description: "Pe 25 martie, Bitza urca pe scena Expirat cu PERSONALE - un concert special, construit ca o confesiune live. Show-ul aduce in prim-plan cele mai...",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e0/6d/00000383099-2937.png",
    event_url: "https://www.iabilet.ro/bilete-bitza-o-personale-o-avanpremiera-album-122989/",
    genres: ["Hip-Hop", "Rap"],
    price: "de la 70 RON",
  },
  {
    source: "iabilet",
    title: "B:pressure pres. Dillinja",
    venue: "Expirat Halele Carol",
    date: "2026-03-26",
    time: "23:00",
    description: "B:Pressure is back. Presenting the 9th season, opening with a legend: Dillinja. Alongside top local talents: Seba 1394 & Kundarini. Visuals by VJ Le...",
    image_url: "https://static3.iabilet.ro/img/db/event/01/df/20/00000381658-4038.png",
    event_url: "https://www.iabilet.ro/bilete-b-pressure-pres-dillinja-122656/",
    genres: ["Drum & Bass", "Underground"],
    price: "de la 60 RON",
  },
  {
    source: "livetickets",
    title: "GH 27.03 | Bagabont pres Bocaseca: un party 100% HIP HOP",
    venue: "Club Guesthouse",
    date: "2026-03-27",
    time: "20:00",
    description: "100% Hip-Hop party at Club Guesthouse presented by Bagabont x Bocaseca. Pure hip-hop all night.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/gh-2703-bagabont-pres-bocaseca-un-party-100-hip-hop/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/gh-2703-bagabont-pres-bocaseca-un-party-100-hip-hop",
    genres: ["Hip-Hop"],
    price: "de la 60 RON",
  },
  {
    source: "livetickets",
    title: "PW - DMC b2b Morgan Boyle, Koler, Mianda at Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-27",
    time: "22:00",
    description: "DMC b2b Morgan Boyle, Koler and Mianda at Platforma Wolff. Underground electronic night.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/pw-dmc-b2b-morgan-boyle-koler-mianda-at-platforma-wolff/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/pw-dmc-b2b-morgan-boyle-koler-mianda-at-platforma-wolff",
    genres: ["Underground", "Electronic"],
    price: "de la 40 RON",
  },
  {
    source: "livetickets",
    title: "MIDNIGHTS presents FAUL & WAD // Fratelli Studio1 // 27.03",
    venue: "Fratelli Studios",
    date: "2026-03-27",
    time: "22:00",
    description: "Midnights presents FAUL & WAD, the French duo behind iconic hits 'Sauti' & 'Changes', at Fratelli Studio1 Bucharest. Table bookings available.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/midnights-presents-faul-wad-fratellistudio1/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/midnights-presents-faul-wad-fratellistudio1",
    genres: ["House", "Electronic", "Club"],
    price: "30 - 300 RON",
  },
  {
    source: "livetickets",
    title: "ANI DE LICEU - Le Dome Bucuresti",
    venue: "Le Dome",
    date: "2026-03-28",
    time: "20:00",
    description: "'High School Years' themed party at Le Dome Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/ani-de-liceu-4/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/ani-de-liceu-4",
    genres: ["Club", "Party"],
    price: "de la 60 RON",
  },
  {
    source: "iabilet",
    title: "ODPL: 1 Tera de Instrumentale",
    venue: "NJoy Club & Garden",
    date: "2026-03-28",
    time: "21:00",
    description: "MARE PETRECERE DE LANSARE! Pe 28 martie, de la 21:00, in Club nJoy, dam startul celei mai tari seri din an!",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e5/9a/00000389335-7a79.jpg",
    event_url: "https://www.iabilet.ro/bilete-odpl-1-tera-de-instrumentale-124314/",
    genres: ["Hip-Hop", "Party"],
    price: "de la 42 RON",
  },
  {
    source: "livetickets",
    title: "PW x DeDans - Gernot (Modeselektor, Moderat), Cosmin TRG at Platforma Wolff",
    venue: "Platforma Wolff",
    date: "2026-03-28",
    time: "22:00",
    description: "Platforma Wolff x DeDans presents Gernot from Modeselektor/Moderat and Cosmin TRG. Major underground electronic event.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/pw-x-dedans-gernot-modeselektor-moderat-cosmin-trg-at-platforma-wolff/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/pw-x-dedans-gernot-modeselektor-moderat-cosmin-trg-at-platforma-wolff",
    genres: ["Techno", "Electronic", "Underground"],
    price: "de la 50 RON",
  },
  {
    source: "livetickets",
    title: "Bairam in Bucuresti by Wayback",
    venue: "Noar Hall",
    date: "2026-03-28",
    time: "22:00",
    description: "Bairam party by Wayback at Noar Hall Bucharest. Balkan-themed club night.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/bairam-in-bucuresti-by-wayback-4/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/bairam-in-bucuresti-by-wayback-4",
    genres: ["Balkan", "Club", "Party"],
    price: "30 - 100 RON",
  },
  {
    source: "livetickets",
    title: "GH 28.03 | Clovis, Suciu",
    venue: "Club Guesthouse",
    date: "2026-03-28",
    time: "23:00",
    description: "Clovis and Suciu DJ night at Club Guesthouse. Underground minimal/techno.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/gh-2803-clovis-suciu/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/gh-2803-clovis-suciu",
    genres: ["Minimal", "Techno", "Underground"],
    price: "de la 40 RON",
  },
  {
    source: "iabilet",
    title: "BBB 2026 - Rick Ross",
    venue: "Laminor Arena",
    date: "2026-03-28",
    time: null,
    description: "The King of Miami lands in Romania. Rick Ross - only at BBB 2026. The edition that raises all standards.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/dd/d7/00000380442-a02c.jpg",
    event_url: "https://www.iabilet.ro/bilete-bbb-2026-rick-ross-122327/",
    genres: ["Hip-Hop", "Rap"],
    price: "de la 179 RON",
  },
  {
    source: "iabilet",
    title: "DELTA HEAVY @ NOISEBREAK: CHAPTER XVI",
    venue: "Quantic",
    date: "2026-04-03",
    time: "22:00",
    description: "After countless nights of DnB & Dubstep, friend reunions and memories made through every beat, we now step into CHAPTER XVI. DELTA HEAVY will turn...",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e1/e1/00000385960-fe4d.png",
    event_url: "https://www.iabilet.ro/bilete-delta-heavy-noisebreak-chapter-xvi-123361/",
    genres: ["DnB", "Dubstep"],
    price: "de la 85 RON",
  },
  {
    source: "livetickets",
    title: "LATINO GANG | Bad Bunny Party - La CASITA | BUCHAREST",
    venue: "Noar Hall",
    date: "2026-04-04",
    time: "22:00",
    description: "Bad Bunny themed party - Latin reggaeton and hip-hop night at Noar Hall Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/latino-gang-bad-bunny-party-la-casita-bucharest/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/latino-gang-bad-bunny-party-la-casita-bucharest",
    genres: ["Reggaeton", "Latin", "Hip-Hop"],
    price: "40 - 70 RON",
  },
  {
    source: "livetickets",
    title: "GH 04.04 | GiGi FM, Rhadoo, oddist",
    venue: "Club Guesthouse",
    date: "2026-04-04",
    time: "23:00",
    description: "GiGi FM, Rhadoo and oddist at Club Guesthouse. Rhadoo is one of the most legendary names in Romanian minimal techno - co-founder of [a]rpiar.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/gh-0404-gigi-fm-rhadoo-oddist/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/gh-0404-gigi-fm-rhadoo-oddist",
    genres: ["Minimal", "Techno", "Underground"],
    price: "de la 55 RON",
  },
  {
    source: "iabilet",
    title: "Escape Party - Hyperjump",
    venue: "Club Mono",
    date: "2026-04-04",
    time: null,
    description: "Pregateste-te pentru un concept 100% nou in Romania: Escape Party - PRIMUL escape room desfasurat in interiorul unui club, in timpul unui party.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e1/d4/00000384805-2d56.png",
    event_url: "https://www.iabilet.ro/bilete-escape-party-hyperjump-123348/",
    genres: ["Club", "Party", "Concept"],
    price: "de la 64 RON",
  },
  {
    source: "iabilet",
    title: "Underground for the Masses III",
    venue: "Quantic",
    date: "2026-04-23",
    time: null,
    description: "Chaos stirs again. Underground for the Masses III returns to Quantic, Bucharest on April 23-25, 2026. A new seal is broken, and the descent continues.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/af/66/00000365596-a3d1.jpg",
    event_url: "https://www.iabilet.ro/bilete-underground-for-the-masses-iii-110438/",
    genres: ["Underground", "Metal", "Bass"],
    price: "de la 650 RON",
  },
  {
    source: "livetickets",
    title: "DELIRIC x SILENT STRIKE x HIP HOP TAKEOVERS | BUCURESTI | Noul Normal: Turneu National 2026",
    venue: "Halo Events Center",
    date: "2026-04-25",
    time: "19:00",
    description: "Deliric x Silent Strike x Hip Hop Takeovers - Bucharest stop of the 'Noul Normal' (New Normal) national tour 2026. Major Romanian hip-hop event.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/deliric-x-silent-strike-x-hip-hop-takeovers-bucuresti-noul-normal-turneu-national/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/deliric-x-silent-strike-x-hip-hop-takeovers-bucuresti-noul-normal-turneu-national",
    genres: ["Hip-Hop", "Rap"],
    price: "de la 139 RON",
  },
  {
    source: "livetickets",
    title: "THE AWAKENING.",
    venue: "Noar Hall",
    date: "2026-04-25",
    time: "21:30",
    description: "THE AWAKENING event at Noar Hall Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/the-awakening/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/the-awakening",
    genres: ["Club", "Electronic"],
    price: "80 - 250 RON",
  },
  {
    source: "livetickets",
    title: "BLACK COFFEE X GAIA",
    venue: "TBA - BUCHAREST",
    date: "2026-05-01",
    time: "15:00",
    description: "Black Coffee - Grammy-winning South African DJ, king of deep/Afro house - comes to Bucharest for a GAIA event. One of the biggest underground...",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/black-coffee-x-gaia/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/black-coffee-x-gaia",
    genres: ["Deep House", "Afro House", "Underground"],
    price: "250 - 900 RON",
  },
  {
    source: "livetickets",
    title: "TRICKY Live @ Club Guesthouse, Bucuresti",
    venue: "Club Guesthouse",
    date: "2026-06-11",
    time: "20:00",
    description: "Tricky (legendary trip-hop pioneer from Massive Attack/solo career) performs live at Club Guesthouse Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/tricky-live-club-guesthouse-bucuresti/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/tricky-live-club-guesthouse-bucuresti",
    genres: ["Trip-Hop", "Electronic", "Underground"],
    price: "de la 148 RON",
  },
  {
    source: "livetickets",
    title: "NOSTALGIA 2026",
    venue: "Federatia Romana de Tir Sportiv",
    date: "2026-06-25",
    time: "17:00",
    description: "NOSTALGIA 2026 festival in Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/nostalgia-2026/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/nostalgia-2026",
    genres: ["Electronic", "Festival"],
    price: "de la 269 RON",
  },
  {
    source: "iabilet",
    title: "Kapital Festival",
    venue: "Arena Nationala",
    date: "2026-07-03",
    time: null,
    description: "Major music festival at Arena Nationala, Bucharest. One of Romania's biggest urban/electronic festival events.",
    image_url: "https://static3.iabilet.ro/img/db/event/01/e5/4e/00000389336-f6a4.png",
    event_url: "https://www.iabilet.ro/bilete-kapital-festival-124238/",
    genres: ["Festival", "Electronic", "Hip-Hop"],
    price: null,
  },
  {
    source: "livetickets",
    title: "Black Rhino Radio presents: Autechre",
    venue: "Club Guesthouse",
    date: "2026-10-07",
    time: "20:00",
    description: "Autechre (legendary IDM/experimental electronic duo from Warp Records) presented by Black Rhino Radio at Club Guesthouse Bucharest.",
    image_url: "https://livetickets-cdn.azureedge.net/itemimages/black-rhino-radio-presents-autechre/Background_MEDIUM.jpg",
    event_url: "https://www.livetickets.ro/bilete/black-rhino-radio-presents-autechre",
    genres: ["IDM", "Experimental Electronic", "Underground"],
    price: "de la 150 RON",
  },
];
